import { Syne } from "next/font/google";
import localFont from "next/font/local";
import LayoutWrapper from "./LayoutWrapper";
import Footer from "./components/Footer";
import Header from "./components/Header";
import ThemeProvider from "./components/ThemeProvider";
import "./globals.css";
// Define your custom Softype font
const softype = localFont({
  src: "../../public/fonts/softype-reg.woff2",
  variable: "--font-softype",
  display: "swap"
});

// Configure Google Font (Syne)
const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  weight: ["400", "800"], // Specify the weights you need
  display: "swap"
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${syne.variable} ${softype.variable}`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <LayoutWrapper>
            <Header />
            {children}
            <Footer />
          </LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
